const express = require('express')
const router = express.Router()
const authRouter = require('../router/auth.Router')
const categoryRouter = require('../router/category.Router')
const resumeRouter = require('../router/resume.Router')
const testRouter = require('../router/test.Router')
const questionRouter = require('../router/question.Router')
const answerRouter = require('../router/answer.Router')
const codingQuestionRouter = require('../router/codingQuestion.Router')
const codingTestRouter = require('../router/codingTest.Router')
const codingSubmissonRouter = require('../router/codingSubmission.Router')
const codrunner = require('../router/codeRunner')
const analyticsRouter = require('../router/analytics.Router')
const aiRouter = require('../router/aiRouter')
const VmRouter = require('../router/runCodeVm.Router')
router.use("/api/v1",authRouter)
router.use("/api/v1",resumeRouter)
router.use("/api/v1",categoryRouter)
router.use("/api/v1",testRouter)
router.use("/api/v1",questionRouter)
router.use("/api/v1",answerRouter)
router.use("/api/v1",codingQuestionRouter)
router.use("/api/v1",codingTestRouter)
router.use("/api/v1",codingSubmissonRouter)
router.use("/api/v1",codrunner)
router.use("/api/v1",analyticsRouter)
router.use("/api/v1",aiRouter)
router.use("/api/v1",VmRouter)
module.exports = router